### ISSUE TITLE
Select Publication Plugin For pom.xml Generation

### ISSUE THREAD

**Issue by TT-S3-D1** [tracetronic/ecu-test-execution-plugin#41]
**Describe the feature request**
As a plugin maintainer I want to have an information complete version of the needed pom.xml.

**Upstream changes**
* [x] select gradle plugin to provide pom.xml
* [x] add information at necessary section in Gradle
* [x] add documentation about pom.xml generation

**Comment by MartinGroscheTT** [comment]
Link to reference in [GitHub ](https://github.com/jenkinsci/ecu-test-execution-plugin/issues/2)
Link to [documentation](https://wiki.tracetronic.de/x/N4JYBQ)

**Comment by MartinGroscheTT** [comment]
Review done by @cwellmtt
